# This file is used to automatically label issues and pull requests based on the files changed.
# It is used by the GitHub Labeler Action: https://github.com/actions/labeler
docs:
  - changed-files:
    - any-glob-to-any-file: "**/README*"

tool-terraform:
  - changed-files:
      - any-glob-to-any-file: "terraform/catalog/modules/**/*"

tool-terragrunt:
  - changed-files:
      - any-glob-to-any-file: "terraform/catalog/units/**/*"
      - any-glob-to-any-file: "terraform/live/**/*"

tool-ansible:
  - changed-files:
      - any-glob-to-any-file: "ansible/**/*"

github_actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

env-dev:
  - changed-files:
    - any-glob-to-any-file: "terraform/live/dev/**"
    - any-glob-to-any-file: "ansible/inventory/dev/**"

env-prod:
  - changed-files:
      - any-glob-to-any-file: "terraform/live/prod/**"
      - any-glob-to-any-file: "ansible/inventory/prod/**"
