# group_vars/k3s_cluster.yml (for prod/k3s.yml inventory)
pve_region: homelab
pve_node_name: pve1
# The following labels are required by https://github.com/sergelogvinov/proxmox-csi-plugin
extra_server_args: >-
  --node-label=topology.kubernetes.io/region={{ pve_region }}
  --node-label=topology.kubernetes.io/zone={{ pve_node_name }}
extra_agent_args: >-
  --node-label=topology.kubernetes.io/region={{ pve_region }}
  --node-label=topology.kubernetes.io/zone={{ pve_node_name }}
