name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v3.0.0
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: shakir85
          numOfAssignee: 1
